"""Auditable control-plane contracts for research automation."""

from .contracts import (
    Actor,
    IdentityBinding,
    Phase,
    PhaseGrant,
    PolicyBinding,
    PolicyMismatchError,
    SideEffect,
    SideEffectLease,
    TaskTicket,
    TicketSnapshot,
    canonical_json,
    canonical_plan_scope_sha256,
    canonical_sha256,
    resolve_policy_source,
)
from .entry_guard import (
    AuthorizationError,
    EntryInventory,
    EntryNotDeclaredError,
    EntryRecord,
    begin_side_effect,
    claim_phase,
    finish_side_effect,
    issue_task_ticket,
    mark_side_effect_in_doubt,
)

__all__ = [
    "Actor",
    "IdentityBinding",
    "Phase",
    "PhaseGrant",
    "PolicyBinding",
    "PolicyMismatchError",
    "SideEffect",
    "SideEffectLease",
    "TaskTicket",
    "TicketSnapshot",
    "canonical_json",
    "canonical_plan_scope_sha256",
    "canonical_sha256",
    "resolve_policy_source",
    "AuthorizationError",
    "EntryInventory",
    "EntryNotDeclaredError",
    "EntryRecord",
    "begin_side_effect",
    "claim_phase",
    "finish_side_effect",
    "issue_task_ticket",
    "mark_side_effect_in_doubt",
]
